#!/bin/bash

### User Variables START ###
windowtomoveto="4" #use count starting at 1

### User Variables END ###


## Script starts here ##

set -euo pipefail
. /etc/crontimerloop.sh
. /etc/windowlabelandmove.sh

echo "Checking multilibs and updating if required"

pkgdir=$(grep '^WORKINGDIR=' /etc/slapt-get/slapt-getrc | sed 's/^WORKINGDIR=//')
multilibdir="${pkgdir}/32multi/"

if ! cd "${multilibdir}"; then
  echo "Unable to cd to ${multilibdir}"
  exit 1
fi

cp -a current/PACKAGES.TXT PACKAGES-OLD.TXT

if ! ctl-fn_timeoutloop "multilib update" 1200 3 lftp -c 'open https://slackware.nl/people/alien/multilib/ ; mirror -c -e current' >/dev/null
then
  exit $rc
fi

echo
if ! diff -q current/PACKAGES.TXT PACKAGES-OLD.TXT > /dev/null 2>&1 ; then
  export windowtomoveto
  export wintomv=${pkgdir}
  wlm-fn_windowlabelandmove
  touch /tmp/multilib_updates
  echo "Multilib updates to install"
else
  echo "Nothing new"
fi

echo
echo
